theme: jekyll-theme-cayman
title: Interactive Generation Of Spectrograms With Vector-Quantized Inpainting
description: "This is the companion website for the eponymous anonymous ISMIR submission <br>
    :construction: :rotating_light: :construction: WEBSITE IN CONSTRUCTION :construction: :rotating_light: :construction:"
github: [metadata]

markdown: kramdown
kramdown:
    math_engine: katex

plugins:
    - jemoji